### PR TITLE
[resource indexer] include dataset redirects in index

### LINKED ISSUE #784: [indexer] incorrect redirect behaviour
### Current Behavior

The URL ncov/global redirects to ncov/gisaid/global/6m however the files for `ncov_global.json` are indexed as their own dataset instead of being grouped with ncov/gisaid/global/6m. 

### Expected behavior

Indexer dataset name resolution should match server URL resolution (redirect) behaviour

### What's going on?

https://github.com/nextstrain/nextstrain.org/blob/2ab05981d13919883e277a3c1f68474541297165/src/redirects.js#L25-L40

Note that there may be other URLs with similar behaviour - the `rediects.js` has many edge cases.

### PR DESCRIPTION
**Pull request by jameshadfield**
Recent work surfaced previous dataset versions across URL redirects¹ by
mirroring the dataset-name resolution process we use for requests on the
server. However it neglected to consider the redirects which are handled
prior to this in the server. This commit adds that functionality as
well. This situation was recently discussed in slack².

To use mpox as an example: the dataset (URL) path "mpox/all-clades" now includes previous versions which were named "monkeypox_mpxv.json", thus extending the snapshot history of this dataset from 2023-09-23 to 2022-06-12.

Our usage of `ncov_global.json` (similarly for other regions) is a lot more complex, because we didn't make clean dataset name switches like monkeypox/mpox.

Looking at the current live index (i.e. before this PR) the `ncov.json` dataset stops being uploaded 2020-04-23 and then starts being uploaded again on 2020-09-03, leaving a large gap in the snapshot history. When we do consider `ncov_global.json` (this PR), we fill in this gap with 99 snapshots. Great!

However `ncov.json` continued to be uploaded through 2021-02-15. In cases such as this the indexer will pick the last uploaded version in a given day. However looking at the data it's clear `ncov.json` was not being rebuilt, simply re-uploaded. For instance, here are nextstrain.org URLs you can view the data in:

* 2020-09-03: [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=U74n6nPfuAYtFoJZDy5mTffmRL9k.91f), [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=y9aBoREy41se0iYGH1.y7i7BtSoGleN.)

* 2021-02-15: [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=WiHRklbcFMB.WpgFMh2PG7g69PK3_Xcl), [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ANBYqAHGJWpFuzusK2gD6e5X_VdTZF6B)

Looking at this data it's clear that we should drop any `ncov.json` datasets after 2020-04-23, which ~I'll add to this PR now~ _update: no need to programmatically drop, see next message in this PR_

Closes #784

¹ <https://github.com/nextstrain/nextstrain.org/pull/783>
² <https://bedfordlab.slack.com/archives/CSKMU6YUC/p1706483980082939>

### CODE REVIEW

**Comment by jameshadfield** [comment]
Here's all the days where we had multiple datasets of different filenames where we have to choose one to represent the "snapshot" for the day. The links will show the dataset in Auspice. The first filename is the one the indexer will use for the day (as it was the most recently updated). The takeaways:

1. `ncov.json` never appears in the index after 2020-04-07, despite it being regularly re-uploaded to S3. Good.
2. 2022-04-30 was the first day we switched from `ncov/open/:region` to `ncov/open/:region/:timeWindow` and we uploaded both sets that day. The datasets are quite different, but the indexer is taking the 6m version which is correct.

* `2022-04-30`| [ncov_open_europe_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_europe_6m.json%3FversionId=GQ6MIpjVRekzUWD5ApEcZiXss18L0bYu), [ncov_open_europe.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_europe.json%3FversionId=g88KI_FVwEoPjDHHrQzYFte0q5ucs0_f)
* `2022-04-30`| [ncov_open_global_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_global_6m.json%3FversionId=iLfm6eJC.fvrP.Atu9nb.DEqxWDwsp63), [ncov_open_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_global.json%3FversionId=35Xc3Eba_hVeK.4adXNPlwsZBbbd4_ne)
* `2022-04-30`| [ncov_open_north-america_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_north-america_6m.json%3FversionId=7EcNfbWQjz2LZBYCsymYFaby1ZrObrTE), [ncov_open_north-america.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_north-america.json%3FversionId=20VzIAOzBFgm24l3GN.YYHJF7llsgKKL)
* `2022-04-30`| [ncov_open_asia_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_asia_6m.json%3FversionId=W4HbbXaTaUABpl4K4npGGn5DLkf0_Pd0), [ncov_open_asia.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_asia.json%3FversionId=0D7PY8FmY7SNSgmbYrJEu_K1Tgx_cY39)
* `2022-04-30`| [ncov_open_oceania_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_oceania_6m.json%3FversionId=N5h9415zEoMdvqpUAn3v7CNcKjkCVwBt), [ncov_open_oceania.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_oceania.json%3FversionId=EZ01Qrg6AFyoxP7IjEvTYGE.glywhG7e)
* `2022-04-30`| [ncov_open_africa_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_africa_6m.json%3FversionId=HLb259ZncGawqsw0tOXkY8gju7legD0T), [ncov_open_africa.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_africa.json%3FversionId=bew4wqt4AO08xQ3f_2eKjEMf8ASsxpLT)
* `2022-04-30`| [ncov_open_south-america_6m.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_south-america_6m.json%3FversionId=yLIX0RrNyC6jDS9J30EsFQAsz_JdoVAE), [ncov_open_south-america.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_open_south-america.json%3FversionId=TH0r1k_0ZeU4A8xG4hvntV4UUKMLSFR1)
* `2021-02-15`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ANBYqAHGJWpFuzusK2gD6e5X_VdTZF6B), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=WiHRklbcFMB.WpgFMh2PG7g69PK3_Xcl)
* `2021-02-08`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=VDg3pDzsaKxVxOSAozFnDalo9fEcaYQo), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=W3YZ62z5gupHsOLZtuZgfjaB4RbO9flX)
* `2021-02-04`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=MblJWQmgx6tzErZ9IZYYWcikvK6KU92N), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=xNH.r0t13hC8dfx2.sTMGz9rD7U8c.cQ)
* `2021-02-02`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=Xxa526ZYz0K0rleSqXF_SuDeR_ffhNZD), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=xXEt4FAqcChoH9LsGSwgP1AyF6rVle2b)
* `2021-01-29`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=QhWYgJOqKqO1zApeg7il7N_IsHFjE19O), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=Grmj13bOqMNpZvrkKzmxWmGlW.sC0Gwx)
* `2021-01-27`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=K401FWVx9uGTcjkilxvSHtsT.xfHQUKi), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=jdunxV4.NHAM_jpZdOd92Wy8TeFIX.7W)
* `2021-01-25`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=rFtB3g6Jyx02Y2D7qCzwYEIRY1FDLtgV), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=_MYK36Bb_BVFv7nS1StccApR6bhyAB5M)
* `2021-01-21`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=YLOC5FRuzAt8TONn8N..4_CkG7gWeOWt), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=K3TGcOvmFzhzYcXyEa52JHDoeFiHVQIV)
* `2021-01-19`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ZTfoO16YGdoUo7K3BJeHWR23_UDQJeR0), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=ypE87kqZghy4.rGzBM_fOmoF.EhEEQg1)
* `2021-01-16`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=lynGxm.oHYRKhmDuOjR6khgXS.T1PTwO), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=0ZNzplvZ1wE88G3m_snCNmf_HQoLyZP6)
* `2021-01-13`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=.ruu3t_Zbvdt9bG7V17tzfJ1pHDxD9UJ), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=xilg.n8JQdL20fkF7NzogTFQFX16nYi6)
* `2021-01-11`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=xRECDiDpiaHvHiQ76kudpiVQ9NCFZJXg), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=FcIO7u0Bd61qAP5F1mfcTcTF1iX1Ax_B)
* `2021-01-07`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=DmZ8D73vWyt2u5B72X7n6g2tgwxD7End), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=GtJ.lwt4r2J2gDPzgj9Ojclh6jY.BlgA)
* `2021-01-05`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=LHOMIDBNzv93BtDvs44ocT1_nCLH0L1T), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=3C72H1YTBzO0OIpNt1__3UMD9oJSBX0J)
* `2021-01-04`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=5ItVh.JMYZC1m_KSkQrXvuAtQWiudJBq), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=NI9TMYT_WaoZKIjBPk8QLUOiSQFs55I9)
* `2021-01-01`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=j0Nn_ePElbEyrIG1nomilXsZrj9Q6et4), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=EdFS.0WMqrZ9Oxr1T6_slLB0TqdZN7Zb)
* `2020-12-28`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=Ycr8HOJAitU3qw_gjOM4xEJMZnSuWh63), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=NSE6UZ_eYEODhfuKrgmo_vXB.DdJ2r76)
* `2020-12-20`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=KPoa4.Dr4l.GP8F0DfTR9XRCx.aWdzMT), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=kqBWCJiQkUEu3DS7Leeug4Jh2NZEmSWP)
* `2020-12-18`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=VvtjizNiIdu_ajIq6VJZdUcXIJ0sPKrG), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=_D0vJc5pmD0eZqoQFJDVEYHIaDMiKyI.)
* `2020-12-16`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=84reaM4oeSBWayVMyGU_LeA6r2z.BfJR), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=hq73df2KZr3.WF3mZbEUqp6fb0CFcxtF)
* `2020-12-10`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ZN3nR0iIsCkB0kfuk46bzpsH6u_BobR6), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=e0ZHdVNRcdgkuIYnMPthrwSMLoq85gjO)
* `2020-12-08`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=oxqNRGWDE_pLvX5IOre3Y45AovqbazmF), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=pG1SPzkbOlvIewrl46au8J3Zw9rBXiwS)
* `2020-12-04`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=WMi7q0a0MY0fhTV_ySqQgg0uDKVnEfHD), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=r1CJYkcumn78F9Usp1kbNsq6oxpip_M5)
* `2020-11-30`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=zavCphUgKaVVF4psYEymEeqEBeYt53.j), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=gZJF71uwyaaKwD3hmQMnZtz9xv89fBN8)
* `2020-11-27`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=xJeq4FU8772HxcVeu9p75pTdWV7RdyvF), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=831O.sX8yxgK3qgxamoVMQSQU6biCjQK)
* `2020-11-26`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=7usMo21mhNhKk2OOKM2VbDiYW_5sVEi2), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=yv_wqNUiiAp_UY.tLgiopKjYh2kdIIhD)
* `2020-11-24`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=3nD4PWfCsDKmG0rv64w2yyMpShveBpXH), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=6uibsJOjOG2czGL0TvErh8SPKFudmupe)
* `2020-11-20`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=fEVgTmZCWRck43xskvGuqGlFqQ8Sp63w), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=UUImvdAB7RYN0wyoNQ_uFNCMSpbLoiyT)
* `2020-11-18`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=.7D9pDthe_T1s13yX7JB2Hl2jOFYLcUO), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=76ECCMZ_5iteu_w3iPKbEWFPLp0CNc3p)
* `2020-11-16`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=vjgQ3RGWLWIQOC8yzzVga6UAQr2qIgiD), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=S3rlfC7hsZA9yEtvG4s3wg10Z.VvACRT)
* `2020-11-14`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ZDWUjlg0o.YgFqBXkyIdkrAhhYGZ6dRB), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=OhA4uEH105ydZaJ37jbLQ.ExDTLDh5o2)
* `2020-11-12`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=dPhpO4567rNj6hPcHbdfOq2iZ5itv0vL), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=to9iMnKP0zPTUKplWc6J6.ertyQZ9jZ7)
* `2020-11-10`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=DPawXgoqwjZ8f7Tp2p2WL032SGI28p6_), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=J9YCxLrthLhesYBkRdP.1eZOs6S2Id3D)
* `2020-11-06`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=WgO1pUmEF7Q7XhC5GhHepcY5lfKkm5vw), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=3jWXf68PyZS3qRE.wXGTb9MJDRHJ8Dmq)
* `2020-11-04`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=kNF88S58TmpC51iwQ..QYtvCOgg7q043), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=vZUx4h75xQ9YP7WB8vNZ3hCcp0Z9RXVA)
* `2020-11-02`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=4MOq_A1Usx`20lPWisllzgahJRJezzSnO),`[ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=evor2ZJK1Nwo.hcGQCoB6aHnnVjLv5v5)
* `2020-10-29`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=2toTxkoESWikJ5MiAmi66XlS3NQnmnDC), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=N.SDowu23GWN6Kt5lHiMAaODz162pgIg)
* `2020-10-27`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=iZp8ZWjYZo7HqI3L97u_KP1Jf7DbisCQ), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=7RxsjM0qEqVrlP_2O0usEkAOmJSeRwGs)
* `2020-10-23`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=7BNHy1.y0KtxibElCzq6AFXMn1PItHWz), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=njnosspKGteG_1WeoGEc4OVJPLKY5c.D)
* `2020-10-21`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=hp52BtAUKxZc0bBwM8f.BeRvUcmeUgow), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=GBKWPTdyFHsYC5vgUYnAIdaLOMYOtco8)
* `2020-10-19`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=I1OS796.tizr2RJYHEthlmf2zf6em9l3), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=3_s_OGtONBR9WcLC4cyLPcx6uA1EMLVB)
* `2020-10-15`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=tM_DbD4..KmBlhanwx9SEmNZQ.78j9Tu), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=Wvrdg_d.Y2OU0fqyqo4FhEaKPWN9tqUE)
* `2020-10-13`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ohVLVBPCeiyoK0tLGTFmXlm2.mOC1IDA), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=0PX.ZXgg1zOg23UG0SdTwZwTGwCeVfUb)
* `2020-10-09`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=7oih4s3FKiAXl4VkE5ocKIWJUQdIhGpl), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=JCE9iB0g1zj3n5c.NChTnVqiAxhpMR9L)
* `2020-10-07`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=ROSd6HCMyJ2px.VtJUEHGosF9qfF3I4W), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=8gLnTZQlCyU_inlYODGjPbNhkdu3O5cb)
* `2020-10-05`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=6fUYPM9h2yJ7fDYlf6ww7mrm8jaFkjjg), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=sarWtQ1DhpcU0DxZgYJ8U_rBVjqp3.0y)
* `2020-10-01`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=EBVFn45t6_X6M2JcfY8XiZoSzt_VX33F), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=0YtiUJ8pbyQgjXIpPj.o5ah0M4l6ANlC)
* `2020-09-29`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=i8z3dRfVAgjFOifz5Lm4bU2q.BiUUz2b), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=mQmSJXoY1p3r50yaqx_ykvNouxEayQVc)
* `2020-09-25`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=oideuHJ3jJwZRNydMtGlRIkaEbUJ2xi3), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=nvBX0B6SuNxrgCC8wLam_FX.kwo832Nz)
* `2020-09-23`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=AhpMI1C_UslyhHYazsUu25aTqtD6oZGm), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=IyyZ9eMwfpMdbs6SGxV7OVbnDhaFphF5)
* `2020-09-21`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=qJ00EebBcRVk5V4p9284oDFzHS9H0xi3), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=SUe.UcughFRcfKgsDMnvlXDUue5.y7os)
* `2020-09-03`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=y9aBoREy41se0iYGH1.y7i7BtSoGleN.), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=U74n6nPfuAYtFoJZDy5mTffmRL9k.91f)
* `2020-04-23`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=W0U.uuhq7riR9hSpUEEQviLR609Y2B9v), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=RsQeYf0.TQCyjsJ35C6EPP8ZqNbwNIVP)
* `2020-04-21`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=K9jdx1SnjW0fJHsLN51gNXiBs7KKIQ.6), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=uaQo28wVo8ckPlDGbowOsolniQOAvolC)
* `2020-04-20`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=LJyWKvoy6AbtE29l92EHkkQQpkvNP6dr), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=J09536aIXQXRCTZhucdxcJBg7frpasUV)
* `2020-04-19`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=AS.M25eydQbNoijIrBboPDLAnLLXyB_i), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=AO_wUBrG_NLFE0cOdrLZFXHgEFtP.shs)
* `2020-04-18`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=pPQ7NikknMJwKU1mrvKEjlWlUMJBjIdF), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=P_d5iT7_pCDX23GVyNsJZyQCeS301pjs)
* `2020-04-17`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=pXH1D7mHAQDTqa.XqiYYko0yUfh91d.I), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=BT3CZ2joFfIpGguibOecE4hKZn.VGUDY)
* `2020-04-16`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=v.4fTWQyq_1pY4teQEUnTHN6DedpugPy), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=eOk4h5dSuGeU.H1XyeTcILIFvv4Kbvas)
* `2020-04-15`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=LXXlfk1zikodD.8GIfiUHtwca2RQUyvc), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=cQoMYAv3ETK1mVPxOB9evvLtAu_jA7Yn)
* `2020-04-14`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=koM4ECmPrkVclRM3D138YdPIYYlNyLll), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=EbnmH_Ugf4v4G_gjAqSjy6a0h3XyyFMV)
* `2020-04-12`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=jVZMU92Yb8y8jcP5ftDMEdldQnjd_jfT), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=6qf._pyjhwaRmjni0HVCWSonh4jhSIT5)
* `2020-04-11`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=QAr6WVKJdAYiEtKHap.ieyKt4zVW.9pW), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=Ltn.YUa3cpk_hSMLxvPoQ0zKtJgnwQGo)
* `2020-04-10`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=e3yNQQcDsE7RwvHe.G.eabc6oSYU7g0g), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=xhHXBZvg5MzGT7v4cfSBa3vfanX6BOb6)
* `2020-04-09`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=c1y3DGD5WKc3k83NIZsk2YIIsS9WXMhS), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=8Zat9M6kbyOopAibLMtpz2XmO_eokF2l)
* `2020-04-08`| [ncov_global.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov_global.json%3FversionId=p1IMDLZxmq.02y6Q6XAusT2vv2CQvfLH), [ncov.json](https://nextstrain.org/fetch/nextstrain-data.s3.amazonaws.com/ncov.json%3FversionId=gECt8XknPmoMn9UeUZorl_8reGXXxW5N)

File: src/redirects.js [hunk 1]
```diff
@@ -141,3 +118,48 @@ export const setup = (app) => {
   }
 
 };
+
+
+/**
+ * Produces a list of dataset redirects. These are defined in a stand-alone
+ * function so that they can be easily reused by the resource indexer to
+ * associate "old" filenames with their new dataset path.
```
Comment (tsibley) [inline src/redirects.js:126]: _non-blocking_

Why a function and not just a static list?

File: src/redirects.js [hunk 2]
```diff
@@ -22,32 +21,10 @@ export const setup = (app) => {
...
-   * recommendations. Note that monkeypox YYYY-MM-DD URLs remain,
-   * e.g. /monkeypox/hmpxv1/2022-09-04
-   */
-  app.route('/monkeypox').get((req, res) => res.redirect('/mpox'));
-  app.route('/monkeypox/mpxv').get((req, res) => res.redirect('/mpox/all-clades'));
-  app.route('/monkeypox/hmpxv1').get((req, res) => res.redirect('/mpox/clade-IIb'));
-  app.route('/monkeypox/hmpxv1/big').get((req, res) => res.redirect('/mpox/lineage-B.1'));
+  /* handle redirects for dataset paths which have changed name */
+  for (const [requestPath, redirectPath] of datasetRedirects()) {
+    app.route(requestPath).get((req, res) => res.redirect(redirectPath));
```
Comment (tsibley) [inline src/redirects.js:26]: _non-blocking_

This doesn't preserve the query of `requestPath`, which is a behaviour change for the `/ncov/…` redirects. Is that intentional? The query was preserved for a reason (see b0d7398ab4aa717c51b4dcca44e5d51a7e688f48 and https://github.com/nextstrain/nextstrain.org/pull/377), though it's not clear if the reason still applies/matters given the passage of time.

**Review by tsibley — APPROVED** [review]

File: src/redirects.js (hunk 2 above)
Comment (jameshadfield) [reply src/redirects.js:26]: Huh. That's no good. I will amend the commit so that queries are preserved across the redirects and also add this to the monkeypox redirects (e.g. `nextstrain.org/monkeypox?c=region` should preserve the query).

Comment (jameshadfield) [reply src/redirects.js]: I've fixed this up, but there's a huge caveat -- here's the salient part of the commit message:

URL queries are now preserved for these redirects for all datasets. This
is a change in behaviour for the monkeypox URLs - as an example
"nextstrain.org/monkeypox/mpxv?c=region" will now redirect to
"nextstrain.org/mpox/all-clades?c=region". There is a very sizeable
caveat to this however, because if the redirect path described here is
subsequently redirected by our `canonicalizeDataset` middleware the
query will be discarded at that point. In practice, all of the ncov
paths and 1/4 of the mpox paths described here are subsequently
redirected and so the URL query is not preserved.
<https://github.com/nextstrain/nextstrain.org/issues/792> tracks this.

**Comment by jameshadfield** [comment]
These redirects don't consider snapshot URLs, e.g. "http://localhost:5000/monkeypox/mpxv@2021-01-01?c=region" redirects appropriately, "http://localhost:5000/monkeypox/mpxv@2023-01-26?c=region" 404s (despite there being a `monkeypox_mpxv.json` uploaded that day. I'll fix this up.

File: src/redirects.js (hunk 1 above)
Comment (tsibley) [reply src/redirects.js:135]: Hmm. I don't find those compelling in this case, FWIW.

- You can use a JSDoc comment with plain old variables.
- Checks can be done on a plain old variable too, done immediately after. (Or in the example of slashes handling like you give, the values can just be canonicalized with a `.map()` instead of erroring.)
- Deferred execution can be nice, but as you say is not applicable here at all.

**Review by tsibley — APPROVED** [review]
